# Generated by Django 4.1.7 on 2023-07-19 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'alignment',
                'verbose_name_plural': 'alignments',
            },
        ),
        migrations.CreateModel(
            name='DivineRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'divine_rank',
                'verbose_name_plural': 'divine_ranks',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'domain',
                'verbose_name_plural': 'domains',
            },
        ),
        migrations.CreateModel(
            name='WorldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'world type',
                'verbose_name_plural': 'worlds types',
            },
        ),
        migrations.CreateModel(
            name='WorldGod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='deities_images')),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.alignment')),
                ('domains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.domain')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.divinerank')),
            ],
            options={
                'verbose_name': 'world god',
                'verbose_name_plural': 'worlds gods',
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='world_images')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('fav_world', models.ManyToManyField(blank=True, related_name='fav_world', to=settings.AUTH_USER_MODEL)),
                ('world_gods', models.ManyToManyField(blank=True, related_name='worlds', to='worlds.worldgod')),
                ('world_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.worldtype')),
            ],
            options={
                'verbose_name': 'world',
                'verbose_name_plural': 'worlds',
            },
        ),
        migrations.CreateModel(
            name='WComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
