# Generated by Django 4.1.7 on 2023-07-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0002_sphere'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='sphere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='worlds.sphere'),
            preserve_default=False,
        ),
    ]
