# Generated by Django 4.1.7 on 2023-08-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0005_alter_world_sphere_alter_world_world_gods_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WComment',
        ),
    ]
