# Generated by Django 4.1.7 on 2023-05-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saved',
        ),
    ]
