# Generated by Django 4.1.7 on 2023-08-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_quality_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
