# Generated by Django 4.1.7 on 2023-09-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
